---
development:
  dialect: postgres
  database: acaturn_api_development
  user: acaturnuser
  password: acaturn
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://acaturnuser:acaturn@127.0.0.1:5432/acaturn_api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://acaturnuser:acaturn@127.0.0.1:5432/acaturn_api_production?sslmode=disable"}}
