---
development:
  dialect: postgres
  database: acaturn_api_development
  user: acaturnuser
  password: acaturn
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: acaturn_api_test
  user: {{ envOr "DATABASE_USER" "acaturnuser" }}
  password: {{ envOr "DATABASE_PASSWORD" "acaturn" }}
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: acaturn_api_production
  user: {{ envOr "DATABASE_USER" "acaturnuser" }}
  password: {{ envOr "DATABASE_PASSWORD" "acaturn" }}
  host: 127.0.0.1
  pool: 5
